hide_topic_views_count:
  type: bool
  default: false
  description:
    en: "Hide the total number of views in the topic stats column on the category homepage."

hide_topic_list_views_count:
  type: bool
  default: false
  description:
    en: "Hide the number of topic views column on all topic list filter pages."

hide_replies_count:
  type: bool
  default: false
  description: 
    en: "Hide the number of replies in the topic stats column on the category homepage."

hide_topic_list_replies_count:
  type: bool
  default: false
  description:
    en: "Hide the number of replies column on all topic list filter pages."

hide_time_since_last_activity:
  type: bool
  default: false
  description:
    en: "Hide the time since last activty in the topic stats column on the category homepage."

hide_topic_list_time_since_last_activity:
  type: bool
  default: false
  description:
    en: "Hide the time since last activty  on all topic list filter pages."

hide_category_topic_stats:
  type: bool
  default: false
  description:
    en: "Hide the topic stats column from the category list on the category homepage."

topic_views_count_font_size:
  type: enum
  default: ""
  choices:
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  description: 
    en: "Topic views count font size in px if above show topic views count setting is enabled. Leave blank to use current default."

topic_views_count_font_weight:
  type: enum
  default: normal
  choices:
    - normal
    - bold
  description: 
    en: "Font weight of the topic views count if show topic views count setting is enabled. Leave blank to use current default."

topic_replies_count_font_size:
  type: enum
  default: ""
  choices:
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  description: 
    en: "Topic replies count font size in px if above show topic views count setting is enabled. Leave blank to use current default."

topic_views_replies_font_weight:
  type: enum
  default: normal
  choices:
    - normal
    - bold
  description: 
    en: "Font weight of the topic replies count if show topic views count setting is enabled. Leave blank to use current default."

time_since_latest_activity_font_size:
  type: enum
  default: ""
  choices:
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  description: 
    en: "Time since last activity font size in px if above show topic views count setting is enabled. Leave blank to use current default."

time_since_latest_activity_font_weight:
  type: enum
  default: normal
  choices:
    - normal
    - bold
  description: 
    en: "Time since last activity font weight if show topic views count setting is enabled. Leave blank to use current default."

