hide_topic_views_count:
  type: bool
  default: false
  description:
    en: "Hide the total number of views in the topic stats column on the category homepage and topic list filter pages."

hide_replies_count:
  type: bool
  default: false
  description: 
    en: "Hide the number of replies in the topic stats column on the category homepage and topic list filter pages."

hide_time_since_last_activity:
  type: bool
  default: false
  description:
    en: "Hide the time since last activty in the topic stats column on the category homepage and topic list filter pages."

hide_category_topic_stats:
  type: bool
  default: false
  description:
    en: "Hide the topic stats from the category list on the category homepage."

hide_all_stats_from_anon:
  type: bool
  default: false
  description:
    en: "Hide all topic stats from anonymous users in both desktop and mobile views."
