hide_topic_views_count:
  type: bool
  default: false
  description:
    en: "Hide the total number of views in the topic stats column on the category homepage."

hide_replies_count:
  type: bool
  default: false
  description: 
    en: "Hide the number of replies in the topic stats column on the category homepage."

hide_time_since_last_activity:
  type: bool
  default: false
  description:
    en: "Hide the time since last activty in the topic stats column on the category homepage."

hide_category_topic_stats:
  type: bool
  default: false
  description:
    en: "Hide the topic stats column from the category list on the category homepage in desktop view."

hide_topic_stats_in_mobile_view:
  type: bool
  default: false
  description:
    en: "Hide the topic stats column from both the category homepage and topic filter list pages in mobile view."

hide_time_since_last_activity_in_mobile_view:
  type: bool
  default: false
  description:
    en: "Hide the time since last activity in topic list filter pages in mobile view."

hide_all_stats_from_anon:
  type: bool
  default: false
  description:
    en: "Hide all topic stats from anonymous users in both desktop and mobile views."
